@echo off
echo Configuring C6809 sources for the DOS(djgpp) platform...

echo # generated by fixdjgpp.bat > makefile
echo MSDOS_TOOL = 1 >> makefile
echo include makefile.all >> makefile

echo Done!



