#!/bin/sh

echo "Configuring C6809 sources for the Linux platform..."

echo "# generated by fixunix.sh" > makefile
echo "LINUX_TOOL = 1" >> makefile
echo "include makefile.all" >> makefile

find . -type f '(' \
   -name '*.sh' \
   ')' \
   -exec sh -c 'printf '\'\\r%s%15s\\r\'' {} '\'\'';
                chmod +x {}' \;

