#!/bin/sh

echo "Configuring C6809 sources for the Macintosh platform..."

echo "# generated by fixmingw.sh" > makefile
echo "MACINTOSH_TOOL = 1" >> makefile
echo "include makefile.all" >> makefile

echo "Done!"
