#!/bin/sh

echo "Configuring c6809 sources for the Windows (MinGW) platform..."

echo "# generated by fixmingw.sh" > makefile
echo "WINDOWS_TOOL = 1" >> makefile
echo "include makefile.all" >> makefile

echo "Done!"
